version: "3.9"

services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.8
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./firebird_wrapper.lua:/usr/local/etc/haproxy/firebird_wrapper.lua
    command: haproxy -d -f /usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 3050:3050
      - 8500:8500

  postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432

  firebird1:
    image: jacobalberty/firebird:3.0
    environment:
      - FIREBIRD_DATABASE=db1.fdb
      - FIREBIRD_USER=docker
      - FIREBIRD_PASSWORD=docker
      - EnableLegacyClientAuth=true

  firebird2:
    image: jacobalberty/firebird:3.0
    environment:
      - FIREBIRD_DATABASE=db2.fdb
      - FIREBIRD_USER=docker
      - FIREBIRD_PASSWORD=docker
      - EnableLegacyClientAuth=true
